In [2]:
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures

from sklearn.linear_model import LinearRegression, RANSACRegressor, LogisticRegression

In [4]:
housing = pd.read_fwf("housing.data", header = None)

In [5]:
housing.columns = ["crime_rate", "zoned_land", "industry", "bounds_river",
"nox_conc", "rooms", "age", "distance", "highways", "tax", "pt_ratio",
"b_estimator", "pop_status", "price"]

In [6]:
housing

crime_rate  zoned_land  industry  bounds_river  nox_conc  rooms   age  \
0       0.00632        18.0      2.31             0     0.538  6.575  65.2   
1       0.02731         0.0      7.07             0     0.469  6.421  78.9   
2       0.02729         0.0      7.07             0     0.469  7.185  61.1   
3       0.03237         0.0      2.18             0     0.458  6.998  45.8   
4       0.06905         0.0      2.18             0     0.458  7.147  54.2   
..          ...         ...       ...           ...       ...    ...   ...   
501     0.06263         0.0     11.93             0     0.573  6.593  69.1   
502     0.04527         0.0     11.93             0     0.573  6.120  76.7   
503     0.06076         0.0     11.93             0     0.573  6.976  91.0   
504     0.10959         0.0     11.93             0     0.573  6.794  89.3   
505     0.04741         0.0     11.93             0     0.573  6.030  80.8   

     distance  highways    tax  pt_ratio  b_estimator  pop_status  price  
0      4.0900         1  296.0      15.3       396.90        4.98   24.0  
1      4.9671         2  242.0      17.8       396.90        9.14   21.6  
2      4.9671         2  242.0      17.8       392.83        4.03   34.7  
3      6.0622         3  222.0      18.7       394.63        2.94   33.4  
4      6.0622         3  222.0      18.7       396.90        5.33   36.2  
..        ...       ...    ...       ...          ...         ...    ...  
501    2.4786         1  273.0      21.0       391.99        9.67   22.4  
502    2.2875         1  273.0      21.0       396.90        9.08   20.6  
503    2.1675         1  273.0      21.0       396.90        5.64   23.9  
504    2.3889         1  273.0      21.0       393.45        6.48   22.0  
505    2.5050         1  273.0      21.0       396.90        7.88   11.9  

[506 rows x 14 columns]

In [7]:
housing.dtypes

crime_rate      float64
zoned_land      float64
industry        float64
bounds_river      int64
nox_conc        float64
rooms           float64
age             float64
distance        float64
highways          int64
tax             float64
pt_ratio        float64
b_estimator     float64
pop_status      float64
price           float64
dtype: object

In [8]:
housing.describe().T

count        mean         std        min       25%         50%  \
crime_rate    506.0    1.716290    2.653510    0.00632    0.0819    0.250895   
zoned_land    506.0   11.363636   23.322453    0.00000    0.0000    0.000000   
industry      506.0   11.136779    6.860353    0.46000    5.1900    9.690000   
bounds_river  506.0    0.069170    0.253994    0.00000    0.0000    0.000000   
nox_conc      506.0    0.554695    0.115878    0.38500    0.4490    0.538000   
rooms         506.0    6.284634    0.702617    3.56100    5.8855    6.208500   
age           506.0   68.574901   28.148861    2.90000   45.0250   77.500000   
distance      506.0    3.696228    1.999689    0.58570    2.0737    3.107300   
highways      506.0    4.332016    1.417166    1.00000    4.0000    4.000000   
tax           506.0  408.237154  168.537116  187.00000  279.0000  330.000000   
pt_ratio      506.0   18.455534    2.164946   12.60000   17.4000   19.050000   
b_estimator   506.0  356.674032   91.294864    0.32000  375.3775  391.440000   
pop_status    506.0   12.653063    7.141062    1.73000    6.9500   11.360000   
price         506.0   22.532806    9.197104    5.00000   17.0250   21.200000   

                     75%        max  
crime_rate      2.326717    9.96654  
zoned_land     12.500000  100.00000  
industry       18.100000   27.74000  
bounds_river    0.000000    1.00000  
nox_conc        0.624000    0.87100  
rooms           6.623500    8.78000  
age            94.075000  100.00000  
distance        5.112625    9.22290  
highways        5.000000    8.00000  
tax           666.000000  711.00000  
pt_ratio       20.200000   22.00000  
b_estimator   396.225000  396.90000  
pop_status     16.955000   37.97000  
price          25.000000   50.00000

In [9]:
housing_prices = housing.price

In [10]:
housing_attributes = housing.drop("price", axis = 1)

In [11]:
housing_attributes.shape, housing_prices.shape

((506, 13), (506,))

# Explore data here then continue


In [12]:
scaler = MinMaxScaler()
scaler.fit_transform(housing_attributes)

array([[0.        , 0.18      , 0.06781525, ..., 0.28723404, 1.        ,
        0.08967991],
       [0.00210738, 0.        , 0.24230205, ..., 0.55319149, 1.        ,
        0.2044702 ],
       [0.00210538, 0.        , 0.24230205, ..., 0.55319149, 0.98973725,
        0.06346578],
       ...,
       [0.00546574, 0.        , 0.42045455, ..., 0.89361702, 1.        ,
        0.10789183],
       [0.01036824, 0.        , 0.42045455, ..., 0.89361702, 0.99130062,
        0.13107064],
       [0.00412541, 0.        , 0.42045455, ..., 0.89361702, 1.        ,
        0.16970199]])

In [13]:
housing_attributes_scaled = scaler.transform(housing_attributes)

In [14]:
# Min and Max values of all comuns
housing_attributes_scaled.min(axis = 0), housing_attributes_scaled.max(axis = 0)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [15]:
#housing_prices_scaled = scaler.fit_transform(housing_prices)

In [16]:
linear_regression = LinearRegression()
linear_regression.fit(housing_attributes_scaled, housing_prices)

LinearRegression()

In [17]:
# Ако колоната се промени с една единица прогнозата се променя със следното число:
linear_regression.coef_

array([  2.08448854,   1.49403979,   0.34690497,   3.00565375,
        -7.54441381,  22.43940145,   0.27658754,  -9.35981793,
         1.35281035,  -1.26826011,  -9.07603108,   3.74177288,
       -19.03479847])

In [18]:
linear_regression.intercept_

23.689291534676975

In [19]:
housing_attributes_scaled[0:10]

array([[0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
        0.57750527, 0.64160659, 0.40572176, 0.        , 0.20801527,
        0.28723404, 1.        , 0.08967991],
       [0.00210738, 0.        , 0.24230205, 0.        , 0.17283951,
        0.5479977 , 0.78269825, 0.50727087, 0.14285714, 0.10496183,
        0.55319149, 1.        , 0.2044702 ],
       [0.00210538, 0.        , 0.24230205, 0.        , 0.17283951,
        0.6943859 , 0.59938208, 0.50727087, 0.14285714, 0.10496183,
        0.55319149, 0.98973725, 0.06346578],
       [0.0026154 , 0.        , 0.06304985, 0.        , 0.15020576,
        0.65855528, 0.44181256, 0.63405965, 0.28571429, 0.06679389,
        0.64893617, 0.99427606, 0.03338852],
       [0.00629805, 0.        , 0.06304985, 0.        , 0.15020576,
        0.68710481, 0.52832132, 0.63405965, 0.28571429, 0.06679389,
        0.64893617, 1.        , 0.09933775],
       [0.0023624 , 0.        , 0.06304985, 0.        , 0.15020576,
        0.54972217, 0.57466

In [20]:
linear_regression.predict(housing_attributes_scaled[0:10])

array([30.10947333, 25.12810976, 31.00785588, 29.04535626, 28.48368175,
       25.44231142, 23.23025545, 20.07399474, 11.87137324, 19.61327434])

In [21]:
prices[0:10].values

NameError: name 'prices' is not defined

In [22]:
random_sample = pd.DataFrame(housing_attributes_scaled).sample(10)

In [23]:
random_sample

0     1         2    3         4         5         6         7   \
253  0.036407  0.22  0.197947  0.0  0.094650  0.900172  0.056643  0.963391   
490  0.020194  0.00  1.000000  0.0  0.460905  0.293543  0.979403  0.143206   
5    0.002362  0.00  0.063050  0.0  0.150206  0.549722  0.574665  0.634060   
328  0.006009  0.00  0.101906  0.0  0.154321  0.442039  0.235839  0.535926   
423  0.707223  0.00  0.646628  0.0  0.471193  0.487066  0.846550  0.166269   
137  0.034739  0.00  0.785557  0.0  0.491770  0.554321  0.983522  0.146355   
259  0.065293  0.20  0.128666  0.0  0.539095  0.628664  1.000000  0.164984   
49   0.021430  0.00  0.236437  0.0  0.129630  0.391071  0.608651  0.637012   
305  0.004866  0.33  0.063050  0.0  0.179012  0.585361  0.568486  0.322361   
489  0.017776  0.00  1.000000  0.0  0.460905  0.355049  0.982492  0.135426   

           8         9         10        11        12  
253  0.857143  0.272901  0.691489  1.000000  0.049945  
490  0.428571  1.000000  0.797872  0.802133  0.771247  
5    0.285714  0.066794  0.648936  0.992990  0.096026  
328  0.428571  0.463740  0.457447  0.963538  0.227373  
423  0.428571  0.914122  0.808511  0.005547  0.594923  
137  0.428571  0.477099  0.914894  0.992889  0.354857  
259  0.571429  0.146947  0.042553  0.987468  0.142660  
49   0.285714  0.087786  0.563830  1.000000  0.399283  
305  0.857143  0.066794  0.617021  0.991074  0.198675  
489  0.428571  1.000000  0.797872  0.866736  0.613687

In [24]:
linear_regression.predict(random_sample)

array([31.97483955,  6.50932942, 25.44231142, 22.65822349, 12.21919358,
       20.29653332, 34.12073437, 17.11878886, 28.54030418, 11.1989868 ])

In [25]:
prices.loc[random_sample.index].values

NameError: name 'prices' is not defined

In [26]:
linear_regression.score(housing_attributes_scaled, housing_prices)

0.7198065414937174

In [27]:
ransac = RANSACRegressor(min_samples=0.9)

In [28]:
ransac.fit(housing_attributes_scaled, housing_prices)

RANSACRegressor(min_samples=0.9)

In [29]:
ransac.estimator_.coef_

array([  0.68999831,   1.68235458,   0.86671406,   2.23964874,
        -5.07810264,  28.97277875,  -2.58057003,  -7.30370445,
         1.75618474,  -2.29329655,  -6.915102  ,   4.76254664,
       -10.99256702])

In [30]:
ransac.estimator_.intercept_

15.457967493181659

In [31]:
ransac.predict(random_sample)

array([34.75339496,  7.21368518, 24.09922685, 21.66637093, 11.37838617,
       20.27859858, 31.14896545, 16.90152048, 27.92163354, 11.08253751])

In [32]:
prices.loc[random_sample.index].values

NameError: name 'prices' is not defined

In [33]:
ransac.score(housing_attributes_scaled, housing_prices)

0.6970114582681401

In [34]:
inliers = housing_attributes_scaled[ransac.inlier_mask_]
outliers = housing_attributes_scaled[~ransac.inlier_mask_]
len(housing_attributes_scaled[ransac.inlier_mask_])

363

In [35]:
ransac.score(inliers, housing_prices.loc[ransac.inlier_mask_])

0.9187517343513729

In [36]:
ransac.score(outliers, housing_prices.loc[~ransac.inlier_mask_])

0.5543119585671119

# Polynomial bit

In [126]:
polynomyal_features = PolynomialFeatures()

In [129]:
housing_attributes_scaled_poly = polynomyal_features.fit_transform(housing_attributes, housing_prices)

In [130]:
housing_attributes_scaled_poly.shape

(506, 105)

In [131]:
quadratic_regression = LinearRegression()
quadratic_regression.fit(housing_attributes_scaled_poly, housing_prices)

LinearRegression()

In [132]:
quadratic_regression.score(housing_attributes_scaled_poly, housing_prices)

0.8863751204789779

# Logistic bit

In [135]:
iris = pd.read_csv("iris.data", header = None)
iris.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class",]

In [136]:
iris_attributes = iris.drop("class" , axis = 1)
iris_class = iris["class"]

In [137]:
iris_attributes_scaled = MinMaxScaler().fit_transform(iris_attributes)

In [138]:
iris_attributes_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [139]:
logistic_regression = LogisticRegression(C = 1e9)

In [140]:
logistic_regression.fit(iris_attributes_scaled, iris_class)

LogisticRegression(C=1000000000.0)

In [141]:
logistic_regression.coef_

array([[-18.29679129,  29.19813694, -37.89417388, -38.3219437 ],
       [ 13.58611302,  -6.58018128,  -8.87560643,  -2.78717031],
       [  4.71067827, -22.61795566,  46.76978031,  41.10911401]])

In [142]:
logistic_regression.intercept_

array([ 25.9014194 ,  14.7266206 , -40.62803999])

In [143]:
logistic_regression.score(iris_attributes_scaled, iris_class)

0.9866666666666667